# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Mod Properties
mod_version=1.21.1
mod_id=quickdisconnectreloaded
mod_name=Quick Disconnect Reloaded
mod_license=MIT
mod_authors=rostpav79
mod_description=Adds a hotkey for instantly leaving a world or multiplayer server
mod_group_id=com.rostpav79.quickdisconnectreloaded

# Fabric API
fabric_version=0.116.5+1.21.1
