# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=26.1.2
mod_id=quickdisconnectreloaded
mod_name=Quick Disconnect Reloaded
mod_license=MIT
mod_authors=rostpav79
mod_description=Adds a hotkey for instantly leaving a world or multiplayer server
mod_group_id=com.rostpav79.quickdisconnectreloaded

# Fabric API
fabric_version=0.155.2+26.1.2
